package ru.application.homemedkit.helpers

const val ALARM_ID = "alarmId"
const val BLANK = ""
const val CHANNEL_ID_EXP = "channel_expiration"
const val CHANNEL_ID_INTAKES = "channel_intakes"
const val CHANNEL_ID_PRE = "channel_prealarm"
const val CIS = "cis"
const val DATABASE_NAME = "medicines"
const val ID = "id"
const val KEY_APP_SYSTEM = "app_system"
const val KEY_APP_THEME = "app_theme"
const val KEY_APP_VIEW = "app_view"
const val KEY_BASIC_SETTINGS = "app_basic_settings"
const val KEY_CHECK_EXP_DATE = "check_exp_date"
const val KEY_CLEAR_CACHE = "clear_app_cache"
const val KEY_CONFIRM_EXIT = "confirm_exit"
const val KEY_DOWNLOAD = "download_images"
const val KEY_DYNAMIC_COLOR = "dynamic_color"
const val KEY_EXP_IMP = "export_import"
const val KEY_FIRST_LAUNCH_INTAKE = "first_launch_intake"
const val KEY_FIXING = "fixing_alarms"
const val KEY_KITS = "kits_group"
const val KEY_LANGUAGE = "language"
const val KEY_ORDER = "sorting_order"
const val KEY_PERMISSIONS = "give_permissions"
const val TAKEN_ID = "takenId"
const val TYPE = "vector_type"