package ru.application.homemedkit.utils


// ======================== Yandex ========================
const val AUTH_URL_YANDEX = "https://oauth.yandex.ru/authorize"
const val CLIENT_ID_YANDEX = "c9efbf4b410d45ce9ee862f9e8c63f3b"
const val CLIENT_SECRET_YANDEX = "9780d6b550a346adbca55df4f3b5874d"
const val REDIRECT_URI_YANDEX = "app://auth/auth_yandex?code={code}"
const val TOKEN_URL_YANDEX = "https://oauth.yandex.ru/token"

// ======================== Constants ========================
const val ALARM_ID = "alarmId"
const val BLANK = ""
const val CHANNEL_ID_EXP = "channel_expiration"
const val CHANNEL_ID_INTAKES = "channel_intakes"
const val CHANNEL_ID_PRE = "channel_prealarm"
const val DATABASE_NAME = "medicines"
const val DEEP_LINK_BASE_URL = "app://notification/full_screen_intake"
const val DEEP_LINK_FULL_SCREEN = "$DEEP_LINK_BASE_URL?takenId={takenId}&medicineId={medicineId}&amount={amount}"
const val ID = "id"
const val IS_ENOUGH_IN_STOCK = "is_enough_in_stock"
const val KEY_ACCESS_TOKEN = "access_token"
const val KEY_APP_SYSTEM = "app_system"
const val KEY_APP_THEME = "app_theme"
const val KEY_APP_VIEW = "app_view"
const val KEY_AUTH_IS_YANDEX = "auth_is_yandex"
const val KEY_AUTO_SYNC_ENABLED = "auto_sync_enabled"
const val KEY_BASIC_SETTINGS = "app_basic_settings"
const val KEY_CHECK_EXP_DATE = "check_exp_date"
const val KEY_CLEAR_CACHE = "clear_app_cache"
const val KEY_CODE_VERIFIER = "pkce_code_verifier"
const val KEY_CONFIRM_EXIT = "confirm_exit"
const val KEY_DOWNLOAD = "download_images"
const val KEY_DYNAMIC_COLOR = "dynamic_color"
const val KEY_FIRST_LAUNCH_INTAKE = "first_launch_intake"
const val KEY_FIXING = "fixing_alarms"
const val KEY_IMPORTED_DATA = "was_data_imported"
const val KEY_IMPORT_EXPORT = "import_export_data"
const val KEY_KITS = "kits_group"
const val KEY_KITS_FILTER = "kits_filter_id"
const val KEY_LANGUAGE = "language"
const val KEY_LAST_SYNC_MILLIS = "last_sync_at_millis"
const val KEY_ORDER = "sorting_order"
const val KEY_PERMISSIONS = "give_permissions"
const val KEY_REFRESH_TOKEN = "refresh_token"
const val KEY_START_PAGE = "start_page"
const val KEY_USE_ALARM_CLOCK = "use_alarm_clock"
const val KEY_USE_VIBRATION_SCAN = "use_vibration_when_scanning"
const val SYNC_MODE = "sync_mode"
const val TAKEN_ID = "takenId"
const val TYPE = "vector_type"
const val WORK_AUTH_FIRST_TIME = "auth_first_time_work"
const val WORK_AUTO_SYNC = "auto_sync_work"