name: Sort Android string resources

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - master

jobs:
  sort-strings:
    if: github.event_name == 'pull_request' && contains(github.event.pull_request.title, 'Weblate') || contains(github.event.pull_request.user.login, 'weblate')
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: 'Setup Python'
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 'Run Script'
        id: sort_script
        run: python .github/scripts/sort_android_strings.py

      - name: 'Commit and push changes'
        if: steps.sort_script.outputs.changes_detected == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git add '**/strings.xml'
          git commit -m "Workflow: сортировка строковых ресурсов"
          
          git push origin HEAD:${{ github.event.pull_request.head.ref }}